const endPoint = 'http://localhost:8081/'
export const endPointAdminReg = endPoint+'adminReg'
export const endPointAuthentication = endPoint+'authenticate'
export const endPointCategory = endPoint+'category/' 
export const endPointSubCategory = endPoint+'sub-category'
export const endPointUsers = endPoint+'add-user'
export const endPointStockManager = endPoint+'stockManager'
export const endPointSalesPerson = endPoint+'salesPerson'
export const endPointCustomerRepresentative = endPoint+'customerRepresentative'
export const endPointProduct = endPoint+'product/'
export const endPointSearchProduct = endPoint+'product/search'
export const endPointProductUpdate = endPoint+'productUpdate'
export const endPointProductAddToCart = endPoint+'add-to-cart'
export const endPointProductOrders = endPoint+'orders'
export const endPointProductRemoveFromCart = endPoint+'remove-from-cart'
export const endPointProductReturnItem = endPoint+'return-item'
export const endPointsetStatus = endPoint+'set-status'
export const endPointCustomerRepresentativeProfile = endPoint+'customerRepresentativeProfile'
export const endPointSalesPersonProfile = endPoint+'salesPersonProfile'
export const endPointUserByEmail = endPoint+'user'
export const endPointFetchAllUsers = endPoint+'users'
export const endPointFetchAllRoles = endPoint+'role/'
export const endPointFetchAllDistributors = endPoint+'distributor/'
export const endPointExportPDF = endPoint+'export'



